name: 'project2_dbt_dskola'
version: '1.0'
config-version: 2

profile: 'project2_dbt_dskola'

# These specify where dbt will look for different types of files.
source-paths: ["models"]

# Configuring target paths for manifest and run results
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Defining models configuration
models:
  dbt_dskola_project:
    # Default configurations for all models
    materialized: table

# Defining sources configuration
# sources:
#   dbt_dskola_project:
#     staging:
#       customers:
#         - +enabled: true
#       orders:
#         - +enabled: true
#       payments:
#         - +enabled: true
#       products:
#         - +enabled: true

# Configuring packages
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6

# Configuring on-run-start and on-run-end hooks
on-run-start: []
on-run-end: []

# Configuring vars
vars: {}